import { mkQ } from './qHelper.js';

export const englishQuestions = [

// ==================== TERM 1 ====================
// アルファベット大文字
mkQ('en1_a01',1,'アルファベット「A」の名前の読み方は？','エイ',['アー','ビー','シー'],'「A」は「エイ」と読みます！「Apple（アップル）」の最初の音は「ア」ですが、文字の名前は「エイ」です。',['alphabet']),
mkQ('en1_a02',1,'アルファベット「B」の名前の読み方は？','ビー',['ベー','ブー','ディー'],'「B」は「ビー」と読みます。「Ball（ボール）」や「Bear（クマ）」の最初の文字です。',['alphabet']),
mkQ('en1_a03',1,'アルファベット「C」の名前の読み方は？','シー',['ケー','チー','エス'],'「C」は「シー」と読みます。「Cat（ネコ）」や「Cake（ケーキ）」の最初の文字です。',['alphabet']),
mkQ('en1_a04',1,'アルファベット「D」の名前の読み方は？','ディー',['デー','ダー','ティー'],'「D」は「ディー」と読みます。「Dog（イヌ）」や「Dance（ダンス）」の最初の文字です。',['alphabet']),
mkQ('en1_a05',1,'アルファベット「E」の名前の読み方は？','イー',['エー','エイ','アイ'],'「E」は「イー」と読みます。「Elephant（ゾウ）」や「Egg（たまご）」の最初の文字です。',['alphabet']),
mkQ('en1_a06',1,'アルファベット「F」の名前の読み方は？','エフ',['フー','フェ','エン'],'「F」は「エフ」と読みます。「Fish（さかな）」や「Flower（花）」の最初の文字です。',['alphabet']),
mkQ('en1_a07',1,'アルファベット「G」の名前の読み方は？','ジー',['ゲー','グー','ジェイ'],'「G」は「ジー」と読みます。「Gorilla（ゴリラ）」や「Green（緑）」の最初の文字です。',['alphabet']),
mkQ('en1_a08',1,'アルファベット「H」の名前の読み方は？','エイチ',['ハー','ヘイ','エッチ'],'「H」は「エイチ」と読みます。「Horse（ウマ）」や「Hello（こんにちは）」の最初の文字です。',['alphabet']),
mkQ('en1_a09',1,'アルファベット「I」の名前の読み方は？','アイ',['イー','アー','ウィ'],'「I」は「アイ」と読みます。「Ice（こおり）」や「I（私）」として使います。',['alphabet']),
mkQ('en1_a10',1,'アルファベット「J」の名前の読み方は？','ジェイ',['ジー','ヤー','ジョイ'],'「J」は「ジェイ」と読みます。「Jump（とぶ）」や「Juice（ジュース）」の最初の文字です。',['alphabet']),
mkQ('en1_a11',1,'アルファベット「K」の名前の読み方は？','ケイ',['カー','キー','ケー'],'「K」は「ケイ」と読みます。「King（王様）」や「Koala（コアラ）」の最初の文字です。',['alphabet']),
mkQ('en1_a12',1,'アルファベット「L」の名前の読み方は？','エル',['エン','エイ','エム'],'「L」は「エル」と読みます。「Lion（ライオン）」や「Lemon（レモン）」の最初の文字です。',['alphabet']),
mkQ('en1_a13',1,'アルファベット「M」の名前の読み方は？','エム',['エン','エル','アム'],'「M」は「エム」と読みます。「Monkey（サル）」や「Milk（ミルク）」の最初の文字です。',['alphabet']),
mkQ('en1_a14',1,'アルファベット「N」の名前の読み方は？','エン',['エム','エル','アン'],'「N」は「エン」と読みます。「Nose（鼻）」や「Night（夜）」の最初の文字です。',['alphabet']),
mkQ('en1_a15',1,'アルファベット「O」の名前の読み方は？','オー',['オウ','アウ','ゼロ'],'「O」は「オー」と読みます。「Orange（オレンジ）」や「Ocean（海）」の最初の文字です。',['alphabet']),
mkQ('en1_a16',1,'アルファベット「P」の名前の読み方は？','ピー',['プー','パー','ビー'],'「P」は「ピー」と読みます。「Penguin（ペンギン）」や「Pizza（ピザ）」の最初の文字です。',['alphabet']),
mkQ('en1_a17',1,'アルファベット「Q」の名前の読み方は？','キュー',['クー','ケイ','ゲー'],'「Q」は「キュー」と読みます。「Queen（女王）」や「Quiz（クイズ）」の最初の文字です。',['alphabet']),
mkQ('en1_a18',1,'アルファベット「R」の名前の読み方は？','アール',['エル','アー','ライ'],'「R」は「アール」と読みます。「Rabbit（ウサギ）」や「Rainbow（虹）」の最初の文字です。',['alphabet']),
mkQ('en1_a19',1,'アルファベット「S」の名前の読み方は？','エス',['シー','エシュ','スー'],'「S」は「エス」と読みます。「Sun（太陽）」や「Snake（ヘビ）」の最初の文字です。',['alphabet']),
mkQ('en1_a20',1,'アルファベット「T」の名前の読み方は？','ティー',['テー','チー','ディー'],'「T」は「ティー」と読みます。「Tiger（トラ）」や「Tree（木）」の最初の文字です。',['alphabet']),
mkQ('en1_a21',1,'アルファベット「U」の名前の読み方は？','ユー',['ウー','ユウ','ウイ'],'「U」は「ユー」と読みます。「Umbrella（かさ）」や「Up（うえ）」の最初の文字です。',['alphabet']),
mkQ('en1_a22',1,'アルファベット「V」の名前の読み方は？','ブイ',['ビー','ヴィ','ウィ'],'「V」は「ブイ」と読みます。「Violin（バイオリン）」や「Vegetable（野菜）」の最初の文字です。',['alphabet']),
mkQ('en1_a23',1,'アルファベット「W」の名前の読み方は？','ダブリュー',['ダブル','ウィ','ダブルユ'],'「W」は「ダブリュー」と読みます。「Water（水）」や「Wind（風）」の最初の文字です。',['alphabet']),
mkQ('en1_a24',1,'アルファベット「X」の名前の読み方は？','エックス',['エグズ','ゼックス','クロス'],'「X」は「エックス」と読みます。「X-ray（レントゲン）」などに使われます。',['alphabet']),
mkQ('en1_a25',1,'アルファベット「Y」の名前の読み方は？','ワイ',['ヤイ','ユー','イー'],'「Y」は「ワイ」と読みます。「Yellow（黄色）」や「Yo-yo（ヨーヨー）」の最初の文字です。',['alphabet']),
mkQ('en1_a26',1,'アルファベット「Z」の名前の読み方は？','ゼット',['ズィー','ズ','ゼン'],'「Z」は「ゼット」と読みます（アメリカでは「ズィー」とも言います）。「Zoo（動物園）」の最初の文字です。',['alphabet']),

// 小文字
mkQ('en1_b01',1,'大文字「A」の小文字はどれ？','a',['q','d','e'],'大文字「A」の小文字は「a」です。形が全然違うので要注意！',['alphabet']),
mkQ('en1_b02',1,'大文字「B」の小文字はどれ？','b',['d','p','q'],'「B」の小文字は「b」です。「d」「p」「q」と形が似ているので間違えやすいです。向きをしっかり確認しましょう！',['alphabet']),
mkQ('en1_b03',1,'大文字「D」の小文字はどれ？','d',['b','p','q'],'「D」の小文字は「d」です。「b」と向きが逆です。右側がまるくなっているのが「d」です。',['alphabet']),
mkQ('en1_b04',1,'大文字「G」の小文字はどれ？','g',['q','p','j'],'「G」の小文字は「g」です。尻尾が下に伸びているのが特徴です。',['alphabet']),
mkQ('en1_b05',1,'大文字「P」の小文字はどれ？','p',['b','d','q'],'「P」の小文字は「p」です。丸が下にある「b」と上下で間違えやすいです。',['alphabet']),
mkQ('en1_b06',1,'大文字「Q」の小文字はどれ？','q',['p','d','b'],'「Q」の小文字は「q」です。丸が右下についているのが「q」です。',['alphabet']),
mkQ('en1_b07',1,'大文字「I」の小文字はどれ？','i',['l','j','!'],'「I」の小文字は「i」です。点（てん）があるのが特徴です。「l（エル）」と間違えやすいです。',['alphabet']),
mkQ('en1_b08',1,'大文字「J」の小文字はどれ？','j',['i','l','y'],'「J」の小文字は「j」です。下に伸びて左にカーブしています。',['alphabet']),
mkQ('en1_b09',1,'大文字「L」と「I」の小文字を区別する方法は？','「l」は縦棒だけ、「i」は点がある',['「L」は縦棒+点、「I」は縦棒だけ','「l」は点あり、「i」は点なし','どちらも同じなので区別できない'],'「I（アイ）」の小文字には点「・」があります。「l（エル）」は点のない縦棒だけです。フォントによってはとても似て見えますが、点があるかどうかで区別できます！',['alphabet'],true),
mkQ('en1_b10',1,'大文字「F」の小文字はどれ？','f',['t','r','e'],'「F」の小文字は「f」です。上がカーブして右向きになっているのが特徴です。',['alphabet']),

// 数字
mkQ('en1_n01',1,'「1」を英語でいうと？','one',['won','wan','un'],'「1」は「one（ワン）」です！犬の鳴き声「ワン」と同じ読み方ですね。',['numbers']),
mkQ('en1_n02',1,'「2」を英語でいうと？','two',['too','to','tue'],'「2」は「two（トゥー）」です！「to（〜へ）」や「too（も）」と同じ読みですが、数字は「two」と書きます。',['numbers']),
mkQ('en1_n03',1,'「3」を英語でいうと？','three',['tree','free','thee'],'「3」は「three（スリー）」です！「tree（木）」と似ていますが「th」で始まります。',['numbers']),
mkQ('en1_n04',1,'「4」を英語でいうと？','four',['for','fore','fur'],'「4」は「four（フォー）」です！「for（〜のため）」と同じ読みです。',['numbers']),
mkQ('en1_n05',1,'「5」を英語でいうと？','five',['fife','hive','dive'],'「5」は「five（ファイブ）」です！じゃんけんの「チョキ」は指が5本のうち2本出すので「two fingers」ですね。',['numbers']),
mkQ('en1_n06',1,'「6」を英語でいうと？','six',['sex','sits','fix'],'「6」は「six（シックス）」です！',['numbers']),
mkQ('en1_n07',1,'「7」を英語でいうと？','seven',['seben','sefen','sevan'],'「7」は「seven（セブン）」です！コンビニの名前にもなっていますね。',['numbers']),
mkQ('en1_n08',1,'「8」を英語でいうと？','eight',['ate','eit','eigt'],'「8」は「eight（エイト）」です！「ate（食べた）」と同じ読みです。',['numbers']),
mkQ('en1_n09',1,'「9」を英語でいうと？','nine',['wine','dine','nein'],'「9」は「nine（ナイン）」です！野球の選手は9人（ナイン）いますね。',['numbers']),
mkQ('en1_n10',1,'「10」を英語でいうと？','ten',['tan','tin','den'],'「10」は「ten（テン）」です！',['numbers']),
mkQ('en1_n11',1,'「11」を英語でいうと？','eleven',['elebven','elefen','eleven'],'「11」は「eleven（イレブン）」です！サッカーのチームは11人（イレブン）です。',['numbers']),
mkQ('en1_n12',1,'「12」を英語でいうと？','twelve',['twelv','twelf','twells'],'「12」は「twelve（トゥエルブ）」です！1年は12か月、時計は12時間です。',['numbers']),
mkQ('en1_n13',1,'「13」を英語でいうと？','thirteen',['thirten','thirdteen','thirtheen'],'「13」は「thirteen（サーティーン）」です！「three（3）」が入っているのがわかりますね。',['numbers']),
mkQ('en1_n14',1,'「20」を英語でいうと？','twenty',['tweny','twentee','twonty'],'「20」は「twenty（トゥエンティ）」です！',['numbers']),
mkQ('en1_n15',1,'「30」を英語でいうと？','thirty',['thirteen','therty','thirdy'],'「30」は「thirty（サーティ）」です！「thirteen（13）」と似ているので注意が必要です。',['numbers']),
mkQ('en1_n16',1,'「100」を英語でいうと？','one hundred',['hundred one','one hundret','hundret'],'「100」は「one hundred（ワン ハンドレッド）」です！',['numbers']),
mkQ('en1_n17',1,'「How many apples?（リンゴはいくつ？）」に対して「5個です」と答えるには？','Five.',['It five.','There are fives.','Five apples are.'],'数を答えるときは「Five.（ファイブ）」のように数字だけでも大丈夫です！',['numbers']),
mkQ('en1_n18',1,'「15」を英語でいうと？','fifteen',['fiveteen','fiften','fivetn'],'「15」は「fifteen（フィフティーン）」です。「five（5）」から「five→fif」に変わります。',['numbers']),
mkQ('en1_n19',1,'英語で「40」は何という？','forty',['fourty','forety','furtee'],'「40」は「forty（フォーティ）」です。「four（4）」から「u」が消えて「forty」になります！',['numbers']),
mkQ('en1_n20',1,'英語で「50」は何という？','fifty',['fifity','fivety','fiftee'],'「50」は「fifty（フィフティ）」です。「five（5）」から変化して「fifty」になります。',['numbers']),

// 曜日
mkQ('en1_d01',1,'月曜日を英語でいうと？','Monday',['Moonday','Moneday','Munday'],'月曜日は「Monday（マンデー）」です！「Moon（月）」が語源です。',['days']),
mkQ('en1_d02',1,'火曜日を英語でいうと？','Tuesday',['Tuseday','Twosday','Tuezday'],'火曜日は「Tuesday（チューズデー）」です！',['days']),
mkQ('en1_d03',1,'水曜日を英語でいうと？','Wednesday',['Wendsday','Wednusday','Wenesday'],'水曜日は「Wednesday（ウェンズデー）」です。「d」が黙字（読まない）なので注意！',['days']),
mkQ('en1_d04',1,'木曜日を英語でいうと？','Thursday',['Thurzday','Thirsday','Thursady'],'木曜日は「Thursday（サーズデー）」です！「Thor（雷神トール）」が語源です。',['days']),
mkQ('en1_d05',1,'金曜日を英語でいうと？','Friday',['Fryday','Freiday','Freeday'],'金曜日は「Friday（フライデー）」です！週末が近くてワクワクする日ですね。',['days']),
mkQ('en1_d06',1,'土曜日を英語でいうと？','Saturday',['Saterday','Satureday','Saterdy'],'土曜日は「Saturday（サタデー）」です！「Saturn（土星）」が語源です。',['days']),
mkQ('en1_d07',1,'日曜日を英語でいうと？','Sunday',['Sundee','Sundy','Sunnday'],'日曜日は「Sunday（サンデー）」です！「Sun（太陽）」が語源です。',['days']),
mkQ('en1_d08',1,'「What day is it today?」の意味は？','今日は何曜日ですか？',['今日は何時ですか？','今日は何日ですか？','今日の天気は？'],'「What day（何曜日）」＋「is it today（今日は）」で「今日は何曜日ですか？」になります。',['days']),
mkQ('en1_d09',1,'学校がある平日を英語で何という？','weekdays',['weekends','schooldays','workweek'],'月〜金の平日を「weekdays（ウィークデーズ）」といいます。土・日は「weekend（週末）」です。',['days']),
mkQ('en1_d10',1,'月曜日〜日曜日のうち「土曜日と日曜日」をまとめて英語でいうと？','weekend',['weekdays','holidays','freedays'],'「weekend（ウィークエンド）」は「week（週）」の「end（終わり）」で土・日のことです！',['days']),

// 月
mkQ('en1_m01',1,'1月を英語でいうと？','January',['Janury','Januery','Jannuary'],'1月は「January（ジャニュアリー）」です！',['months']),
mkQ('en1_m02',1,'2月を英語でいうと？','February',['Febuary','Feburary','Februery'],'2月は「February（フェブラリー）」です！',['months']),
mkQ('en1_m03',1,'3月を英語でいうと？','March',['Marth','Martch','Marsh'],'3月は「March（マーチ）」です！卒業式の季節ですね。',['months']),
mkQ('en1_m04',1,'4月を英語でいうと？','April',['Aprel','Arpil','Aprile'],'4月は「April（エイプリル）」です！4月1日はApril Fool\'s Day（エイプリルフール）です。',['months']),
mkQ('en1_m05',1,'5月を英語でいうと？','May',['Mae','Mey','Mai'],'5月は「May（メイ）」です！短くて覚えやすいですね。',['months']),
mkQ('en1_m06',1,'6月を英語でいうと？','June',['Jun','Juin','Junne'],'6月は「June（ジューン）」です！雨の多い梅雨の月ですね。',['months']),
mkQ('en1_m07',1,'7月を英語でいうと？','July',['Julay','Jooly','Juli'],'7月は「July（ジュライ）」です！夏休みが始まる月ですね。',['months']),
mkQ('en1_m08',1,'8月を英語でいうと？','August',['Augost','Augast','Auguts'],'8月は「August（オーガスト）」です！一番暑い夏の月です。',['months']),
mkQ('en1_m09',1,'9月を英語でいうと？','September',['Septeber','Sepember','Semtember'],'9月は「September（セプテンバー）」です！「sept」はラテン語で「7」ですが、今は9月です。',['months']),
mkQ('en1_m10',1,'10月を英語でいうと？','October',['Octover','Octaber','Oktober'],'10月は「October（オクトーバー）」です！「oct」は「8本足のタコ」のタコ（octopus）と同じ語源です。',['months']),
mkQ('en1_m11',1,'11月を英語でいうと？','November',['Novermber','Nobember','Novenber'],'11月は「November（ノーベンバー）」です！「nov」はラテン語で「9」です。',['months']),
mkQ('en1_m12',1,'12月を英語でいうと？','December',['Decenber','Desember','Decmber'],'12月は「December（ディセンバー）」です！クリスマスの月ですね。「dec」は「10」が語源です。',['months']),
mkQ('en1_m13',1,'「When is your birthday?（誕生日はいつ？）」と聞かれて「7月生まれです」と答えるには？','My birthday is in July.',['My birthday is July.','Birthday is on July.','I born July.'],'月を使うときは「in（〜に）」を使います。「My birthday is in ～.」が正しい形です！',['months']),
mkQ('en1_m14',1,'英語で月の名前を書くとき、最初の文字は？','大文字（Capital letter）',['小文字（lowercase）','どちらでもよい','月によって違う'],'月の名前（January, Februaryなど）は必ず「大文字」で始めます！曜日（Monday, Tuesdayなど）も同じです。',['months'],true),

// 色
mkQ('en1_c01',1,'赤色を英語でいうと？','red',['rad','reed','rid'],'赤は「red（レッド）」です！',['colors']),
mkQ('en1_c02',1,'青色を英語でいうと？','blue',['blew','blow','blou'],'青は「blue（ブルー）」です！「blew（吹いた）」と同じ読みですが書き方が違います。',['colors']),
mkQ('en1_c03',1,'黄色を英語でいうと？','yellow',['yelow','yello','yollow'],'黄色は「yellow（イエロー）」です！「l」が2つ続くので気をつけて！',['colors']),
mkQ('en1_c04',1,'緑色を英語でいうと？','green',['grean','gren','grene'],'緑は「green（グリーン）」です！',['colors']),
mkQ('en1_c05',1,'白色を英語でいうと？','white',['wite','whiet','wight'],'白は「white（ホワイト）」です！「wh」は「ホ」という音になります。',['colors']),
mkQ('en1_c06',1,'黒色を英語でいうと？','black',['blac','balck','bleck'],'黒は「black（ブラック）」です！',['colors']),
mkQ('en1_c07',1,'ピンク色を英語でいうと？','pink',['pank','penk','ponk'],'ピンクはそのまま「pink（ピンク）」です！',['colors']),
mkQ('en1_c08',1,'オレンジ色を英語でいうと？','orange',['orang','oranje','ornge'],'オレンジはそのまま「orange（オレンジ）」です！果物のオレンジと同じ単語です。',['colors']),
mkQ('en1_c09',1,'紫色を英語でいうと？','purple',['purpel','violet','purle'],'紫は「purple（パープル）」です！「violet（バイオレット）」とも言います。',['colors']),
mkQ('en1_c10',1,'茶色を英語でいうと？','brown',['bround','brawn','broen'],'茶色は「brown（ブラウン）」です！',['colors']),
mkQ('en1_c11',1,'「What color do you like?（何色が好きですか？）」に対して「青が好きです」と答えるには？','I like blue.',['I like the blue.','My color is blue.','Blue I like.'],'「I like ～.」の形で好きなものを伝えます。色の前に「the」はつけません！',['colors']),
mkQ('en1_c12',1,'虹（にじ）の色は英語で「ROYGBIV」と覚えます。「G」は何色？','Green（緑）',['Gold（金）','Gray（灰）','Grape（ブドウ）'],'虹の色は英語で「Red, Orange, Yellow, Green, Blue, Indigo, Violet」の頭文字をとって「ROYGBIV（ロイジビブ）」と覚えます！',['colors'],true),

// あいさつ
mkQ('en1_gr01',1,'「こんにちは！」を英語でいうと？','Hello!',['Goodbye!','Thank you!','Sorry!'],'あいさつの基本は「Hello（ハロー）！」です！「Hi（ハイ）」も同じ意味です。',['greetings']),
mkQ('en1_gr02',1,'「おはようございます」を英語でいうと？','Good morning.',['Good afternoon.','Good evening.','Good night.'],'朝のあいさつは「Good morning（グッド モーニング）」です！',['greetings']),
mkQ('en1_gr03',1,'「こんにちは（午後のあいさつ）」を英語でいうと？','Good afternoon.',['Good morning.','Good evening.','Good noon.'],'午後のあいさつは「Good afternoon（グッド アフタヌーン）」です！',['greetings']),
mkQ('en1_gr04',1,'「こんばんは」を英語でいうと？','Good evening.',['Good morning.','Good night.','Good afternoon.'],'夜のあいさつは「Good evening（グッド イーブニング）」です！',['greetings']),
mkQ('en1_gr05',1,'「おやすみなさい」を英語でいうと？','Good night.',['Good evening.','Sleep well.','Good bye.'],'寝るときのあいさつは「Good night（グッド ナイト）」です！',['greetings']),
mkQ('en1_gr06',1,'「さようなら」を英語でいうと？','Goodbye.',['See later.','Farewell now.','Good morning.'],'別れるときは「Goodbye（グッバイ）」です。「See you!（またね）」もよく使います。',['greetings']),
mkQ('en1_gr07',1,'「ありがとうございます」を英語でいうと？','Thank you.',['Thanks you.','Thank you very.','Thankyou.'],'感謝するときは「Thank you（サンキュー）」です！もっと丁寧にするには「Thank you very much.（とてもありがとう）」と言います。',['greetings']),
mkQ('en1_gr08',1,'「どういたしまして」を英語でいうと？','You\'re welcome.',['No thank you.','Your welcome.','Don\'t mention.'],'「Thank you.」と言われたら「You\'re welcome（ユアー ウェルカム）」と返します！',['greetings']),
mkQ('en1_gr09',1,'「ごめんなさい」を英語でいうと？','I\'m sorry.',['Excuse me.','I\'m sorry me.','Sorry thank you.'],'謝るときは「I\'m sorry（アイム ソーリー）」です。「Excuse me（エクスキューズ ミー）」は「すみません（呼びかけ）」です。',['greetings']),
mkQ('en1_gr10',1,'「お元気ですか？」を英語でいうと？','How are you?',['Who are you?','Where are you?','What are you?'],'「How are you?（ハウ アー ユー）」は「お元気ですか？」という意味です！答え方は「I\'m fine（元気です）」です。',['greetings']),
mkQ('en1_gr11',1,'「はじめまして」を英語でいうと？','Nice to meet you.',['Good to see you.','I meet you nice.','How do you meet.'],'初めて会う人には「Nice to meet you.（ナイス トゥ ミート ユー）」と言います！',['greetings']),
mkQ('en1_gr12',1,'「いただきます」に一番近い英語表現は？','Let\'s eat! / Bon appétit!',['Thank you for the food.','I will eat now.','Start eating please.'],'英語に「いただきます」に完全に対応する言葉はありません。「Let\'s eat!」や「Bon appétit!（ボナペティ）」などを使います。文化の違いですね！',['greetings'],true),
mkQ('en1_gr13',1,'「お名前は何ですか？」を英語でいうと？','What\'s your name?',['What is you name?','What your name?','Where\'s your name?'],'「What\'s your name?（ワッツ ユア ネーム）」が正しい表現です。「What\'s = What is」の短縮形です。',['greetings']),
mkQ('en1_gr14',1,'「私の名前は〇〇です」と答えるには？','My name is ○○.',['I name is ○○.','My name ○○.','Name me ○○.'],'自己紹介するときは「My name is ～.（マイ ネーム イズ）」を使います！',['greetings']),

// 動物
mkQ('en1_ani01',1,'「犬」を英語でいうと？','dog',['dag','doog','hound'],'犬は「dog（ドッグ）」です！',['animals']),
mkQ('en1_ani02',1,'「猫」を英語でいうと？','cat',['kat','hat','bat'],'猫は「cat（キャット）」です！',['animals']),
mkQ('en1_ani03',1,'「ウサギ」を英語でいうと？','rabbit',['rabit','rabbat','habbit'],'ウサギは「rabbit（ラビット）」です！「b」が2つ続くので注意！',['animals']),
mkQ('en1_ani04',1,'「クマ」を英語でいうと？','bear',['beer','bare','pare'],'クマは「bear（ベアー）」です。「beer（ビール）」と似ていますが違います！',['animals']),
mkQ('en1_ani05',1,'「ライオン」を英語でいうと？','lion',['loin','lian','liion'],'ライオンは「lion（ライオン）」です！',['animals']),
mkQ('en1_ani06',1,'「ゾウ」を英語でいうと？','elephant',['elefant','elaphant','elifant'],'ゾウは「elephant（エレファント）」です！「ph」は「f」の音です。',['animals']),
mkQ('en1_ani07',1,'「サル」を英語でいうと？','monkey',['monky','munkey','moneky'],'サルは「monkey（モンキー）」です！',['animals']),
mkQ('en1_ani08',1,'「トラ」を英語でいうと？','tiger',['tigger','teger','tyger'],'トラは「tiger（タイガー）」です！',['animals']),
mkQ('en1_ani09',1,'「キリン」を英語でいうと？','giraffe',['girafe','jiraffe','giraf'],'キリンは「giraffe（ジラフ）」です！「ff」が続く珍しいスペルです。',['animals']),
mkQ('en1_ani10',1,'「ペンギン」を英語でいうと？','penguin',['pengin','pinguine','pengwin'],'ペンギンは「penguin（ペングウィン）」です！',['animals']),
mkQ('en1_ani11',1,'「ヘビ」を英語でいうと？','snake',['sneak','snoke','slake'],'ヘビは「snake（スネーク）」です！',['animals']),
mkQ('en1_ani12',1,'「カエル」を英語でいうと？','frog',['fog','flog','forg'],'カエルは「frog（フロッグ）」です！',['animals']),
mkQ('en1_ani13',1,'「魚」を英語でいうと？','fish',['fiss','feesh','fich'],'魚は「fish（フィッシュ）」です！',['animals']),
mkQ('en1_ani14',1,'「鳥」を英語でいうと？','bird',['bired','burd','berd'],'鳥は「bird（バード）」です！',['animals']),
mkQ('en1_ani15',1,'「ウシ」を英語でいうと？','cow',['caw','kow','cou'],'ウシは「cow（カウ）」です！牛乳は「cow\'s milk」ともいいます。',['animals']),
mkQ('en1_ani16',1,'「ウマ」を英語でいうと？','horse',['hors','norse','hurse'],'ウマは「horse（ホース）」です！',['animals']),
mkQ('en1_ani17',1,'「ヒツジ」を英語でいうと？','sheep',['ship','shep','cheep'],'ヒツジは「sheep（シープ）」です！なんと1頭でも複数でも「sheep」です。',['animals']),
mkQ('en1_ani18',1,'「ブタ」を英語でいうと？','pig',['big','peg','pig'],'ブタは「pig（ピッグ）」です！',['animals']),
mkQ('en1_ani19',1,'「チョウ（蝶）」を英語でいうと？','butterfly',['butterflye','flybutterr','mothfly'],'チョウは「butterfly（バタフライ）」です！「butter（バター）」＋「fly（飛ぶ）」ですね。',['animals']),
mkQ('en1_ani20',1,'「クジラ」を英語でいうと？','whale',['wale','whail','wall'],'クジラは「whale（ウェイル）」です！「wh」が「ウ」の音になります。',['animals']),
mkQ('en1_ani21',1,'「イルカ」を英語でいうと？','dolphin',['dolpin','dolfin','dalphine'],'イルカは「dolphin（ドルフィン）」です！「ph」は「f」の音です。',['animals']),
mkQ('en1_ani22',1,'「パンダ」を英語でいうと？','panda',['pander','pandas','panta'],'パンダは「panda（パンダ）」です！世界共通の名前ですね。',['animals']),
mkQ('en1_ani23',1,'「リス」を英語でいうと？','squirrel',['squiral','skwirrel','sqirrel'],'リスは「squirrel（スクウィレル）」です！スペルが難しいですね。',['animals'],true),
mkQ('en1_ani24',1,'「コウモリ」を英語でいうと？','bat',['back','bad','ban'],'コウモリは「bat（バット）」です！野球のバットと同じ単語です。',['animals']),
mkQ('en1_ani25',1,'犬の鳴き声を英語で表すと？','Woof! / Bow-wow!',['Moo!','Meow!','Oink!'],'英語では犬は「Woof（ウーフ）」や「Bow-wow（バウワウ）」と鳴きます。日本語の「ワン」とは違いますね。',['animals']),

// 食べ物・くだもの
mkQ('en1_f01',1,'「リンゴ」を英語でいうと？','apple',['aple','appel','aplle'],'リンゴは「apple（アップル）」です！アルファベットを覚えるときによく使う単語ですね。',['food']),
mkQ('en1_f02',1,'「バナナ」を英語でいうと？','banana',['bananna','banena','benana'],'バナナは「banana（バナナ）」です！スペルに注意：「a」「n」「a」「n」「a」です。',['food']),
mkQ('en1_f03',1,'「イチゴ」を英語でいうと？','strawberry',['strowberry','stawberry','strawbery'],'イチゴは「strawberry（ストロベリー）」です！',['food']),
mkQ('en1_f04',1,'「スイカ」を英語でいうと？','watermelon',['watermalon','wattermelon','watermellon'],'スイカは「watermelon（ウォーターメロン）」です！「water（水）」＋「melon（メロン）」ですね。',['food']),
mkQ('en1_f05',1,'「ブドウ」を英語でいうと？','grape',['graep','grep','grpe'],'ブドウは「grape（グレープ）」です！',['food']),
mkQ('en1_f06',1,'「モモ（桃）」を英語でいうと？','peach',['peech','beech','paech'],'モモは「peach（ピーチ）」です！ピーチ姫もここから来ています。',['food']),
mkQ('en1_f07',1,'「パン」を英語でいうと？','bread',['braid','bread','bred'],'パンは「bread（ブレッド）」です！日本語のパンはポルトガル語「pão」から来ています。',['food']),
mkQ('en1_f08',1,'「ごはん（米）」を英語でいうと？','rice',['lice','mice','rise'],'ごはんは「rice（ライス）」です！',['food']),
mkQ('en1_f09',1,'「ピザ」を英語でいうと？','pizza',['piza','pitsa','pissa'],'ピザは「pizza（ピッツァ）」です！「zz」が続くイタリア語由来の単語です。',['food']),
mkQ('en1_f10',1,'「チョコレート」を英語でいうと？','chocolate',['choclate','chocolet','chockolate'],'チョコレートは「chocolate（チョコレット）」です！',['food']),
mkQ('en1_f11',1,'「アイスクリーム」を英語でいうと？','ice cream',['icecream','ais cream','ice creame'],'アイスクリームは「ice cream（アイス クリーム）」です！2語に分けて書くのが一般的です。',['food']),
mkQ('en1_f12',1,'「ハンバーガー」を英語でいうと？','hamburger',['hamburguer','hamberger','hamburge'],'ハンバーガーは「hamburger（ハンバーガー）」です！',['food']),
mkQ('en1_f13',1,'「牛乳・ミルク」を英語でいうと？','milk',['milch','meelk','milik'],'牛乳は「milk（ミルク）」です！',['food']),
mkQ('en1_f14',1,'「ケーキ」を英語でいうと？','cake',['caek','kake','cak'],'ケーキは「cake（ケイク）」です！',['food']),
mkQ('en1_f15',1,'「味噌汁」を英語で説明するには？','miso soup',['soy soup','rice soup','bean paste'],'味噌汁は英語で「miso soup（ミソ スープ）」といいます。日本食を英語で説明できると素敵ですね！',['food']),
mkQ('en1_f16',1,'「すし」を英語でいうと？','sushi',['suushi','zushi','shusi'],'すしは「sushi（スシ）」です！今や世界中で通じる日本語です！',['food']),
mkQ('en1_f17',1,'「水」を英語でいうと？','water',['watter','waater','woter'],'水は「water（ウォーター）」です！',['food']),
mkQ('en1_f18',1,'「卵」を英語でいうと？','egg',['eeg','eg','ekk'],'卵は「egg（エッグ）」です！「g」が2つ続きます。',['food']),
mkQ('en1_f19',1,'「にんじん」を英語でいうと？','carrot',['caret','carot','carott'],'にんじんは「carrot（キャロット）」です！「r」が2つ続きます。',['food']),
mkQ('en1_f20',1,'「トマト」を英語でいうと？','tomato',['tomate','tomota','tomotto'],'トマトは「tomato（トメイトウ）」です！英語では少し発音が変わります。',['food']),

// 体の部位
mkQ('en1_body01',1,'「頭」を英語でいうと？','head',['heed','hade','hed'],'頭は「head（ヘッド）」です！',['body']),
mkQ('en1_body02',1,'「目」を英語でいうと？','eye',['aye','ai','i'],'目は「eye（アイ）」です！「I（私）」と同じ発音です。',['body']),
mkQ('en1_body03',1,'「鼻」を英語でいうと？','nose',['knows','noze','noss'],'鼻は「nose（ノーズ）」です！「knows（知っている）」と同じ発音です。',['body']),
mkQ('en1_body04',1,'「口」を英語でいうと？','mouth',['moat','mous','moouth'],'口は「mouth（マウス）」です！コンピューターの「マウス」は「mouse（ネズミ）」で別の単語です。',['body']),
mkQ('en1_body05',1,'「耳」を英語でいうと？','ear',['year','here','air'],'耳は「ear（イアー）」です！「year（年）」に似ていますね。',['body']),
mkQ('en1_body06',1,'「手」を英語でいうと？','hand',['hant','hend','had'],'手は「hand（ハンド）」です！',['body']),
mkQ('en1_body07',1,'「足（あし）」を英語でいうと？','leg / foot',['feet / feet','leg / hand','arm / foot'],'「leg（レッグ）」は膝から下の「足全体」、「foot（フット）」は「足の裏・足先」を指します。',['body']),
mkQ('en1_body08',1,'「肩」を英語でいうと？','shoulder',['shulder','shouder','sholder'],'肩は「shoulder（ショルダー）」です！ショルダーバッグはここから来ています。',['body']),
mkQ('en1_body09',1,'「お腹」を英語でいうと？','stomach',['stomac','belly','stumach'],'お腹は「stomach（スタマック）」です。「belly（ベリー）」も使われます。',['body']),
mkQ('en1_body10',1,'「背中」を英語でいうと？','back',['beck','bak','bace'],'背中は「back（バック）」です！ランドセルの「back」はここから来ています。',['body']),

// 自己紹介・What do you like?
mkQ('en1_si01',1,'「私は〜が好きです」を英語でいうと？','I like ~.',['I love ~.（強め）','I have ~.','I want ~.'],'「I like ～.（アイ ライク）」で好きなものを伝えます！大好き！というときは「I love ～.」を使います。',['self_intro']),
mkQ('en1_si02',1,'「あなたは何が好きですか？」と英語で聞くには？','What do you like?',['What you like?','What are you like?','Do you like what?'],'「What do you like?（ワット ドゥ ユー ライク）」が正しい形です！',['self_intro']),
mkQ('en1_si03',1,'「私はサッカーが好きです」を英語でいうと？','I like soccer.',['I like a soccer.','I likes soccer.','Soccer I like.'],'「I like soccer.」が正しいです！「soccer」の前に「a」はつけません。',['self_intro']),
mkQ('en1_si04',1,'「あなたは何歳ですか？」と英語で聞くには？','How old are you?',['How years are you?','What age do you?','How old you are?'],'「How old are you?（ハウ オールド アー ユー）」が「何歳ですか？」という意味です！',['self_intro']),
mkQ('en1_si05',1,'「私は10歳です」と英語でいうと？','I\'m ten years old.',['I have ten years.','My age is ten years old.','I ten years old.'],'「I\'m ～ years old.（アイム ～ ヤーズ オールド）」が正しい形です！',['self_intro']),
mkQ('en1_si06',1,'「あなたはどこから来ましたか？」と英語で聞くには？','Where are you from?',['Where do you from?','From where you?','What are you from?'],'「Where are you from?（ウェア アー ユー フロム）」が正しいです！「What」ではなく「Where（どこ）」を使います。',['self_intro']),
mkQ('en1_si07',1,'「私は日本出身です」と英語でいうと？','I\'m from Japan.',['I am of Japan.','I come Japan.','I\'m Japan.'],'「I\'m from ～.（アイム フロム）」で出身地を伝えます！',['self_intro']),
mkQ('en1_si08',1,'「私はピカチュウが好きです」を英語でいうと？','I like Pikachu.',['I liking Pikachu.','Me like Pikachu.','I am like Pikachu.'],'「I like ～.」の形です。「I liking」のように「ing」をつけてはいけません！',['self_intro']),
mkQ('en1_si09',1,'「誕生日はいつですか？」を英語でいうと？','When is your birthday?',['What is your birthday?','Where is your birthday?','How is your birthday?'],'「When（いつ）」を使います。「What」ではありません！',['self_intro']),
mkQ('en1_si10',1,'「私は音楽が好きです」を英語でいうと？','I like music.',['I like a music.','I enjoy music.','Music I like.'],'「I like music.」が正しいです。「music（音楽）」の前に「a」は不要です！',['self_intro']),
mkQ('en1_si11',1,'「好きな食べ物は何ですか？」を英語でいうと？','What food do you like?',['What do you eat food?','Which your food?','What food are you?'],'「What food do you like?（何の食べ物が好きですか）」が正しいです！',['self_intro']),
mkQ('en1_si12',1,'「好きな色は何ですか？」を英語でいうと？','What color do you like?',['Which color like you?','What is your color?','Do you color like?'],'「What color do you like?（何色が好きですか）」が正しい表現です！',['self_intro']),
mkQ('en1_si13',1,'「私は水泳が好きではありません」を英語でいうと？','I don\'t like swimming.',['I not like swimming.','I dislike swimming.','I no like swimming.'],'「好きではない」は「don\'t like（ドント ライク）」を使います。「not like」だけではNGです！',['self_intro']),
mkQ('en1_si14',1,'「私はラーメンが大好きです！」を英語でいうと？','I love ramen!',['I very like ramen!','I really love ramen!','I much like ramen!'],'「大好き！」のときは「love（ラブ）」を使います。「I love ～!」で強い気持ちが伝わります！',['self_intro']),
mkQ('en1_si15',1,'クラスで友達に「あなたはどんな食べ物が好き？」と聞きたいとき，一番自然な英語は？','What food do you like?',['What food you like?','What do you like food?','How food do you like?'],'「What food do you like?」が最も自然です。語順に注意しましょう！',['self_intro']),

// 教室のもの
mkQ('en1_cl01',1,'「本（教科書）」を英語でいうと？','book',['boke','bock','booc'],'本は「book（ブック）」です！',['classroom']),
mkQ('en1_cl02',1,'「えんぴつ」を英語でいうと？','pencil',['pensil','pensel','pencell'],'えんぴつは「pencil（ペンシル）」です！',['classroom']),
mkQ('en1_cl03',1,'「消しゴム」を英語でいうと？','eraser',['erazer','erasor','irazer'],'消しゴムは「eraser（イレーザー）」です！「erase（消す）」＋「er（もの）」です。',['classroom']),
mkQ('en1_cl04',1,'「ものさし（定規）」を英語でいうと？','ruler',['ruller','roller','roler'],'定規は「ruler（ルーラー）」です！',['classroom']),
mkQ('en1_cl05',1,'「かばん（ランドセル）」を英語でいうと？','bag',['back','buck','box'],'かばんは「bag（バッグ）」です！',['classroom']),
mkQ('en1_cl06',1,'「先生」を英語でいうと？','teacher',['teatcher','teecher','techer'],'先生は「teacher（ティーチャー）」です！「teach（教える）」＋「er（人）」です。',['classroom']),
mkQ('en1_cl07',1,'「黒板」を英語でいうと？','blackboard',['darkboard','chalkboard','blackbored'],'黒板は「blackboard（ブラックボード）」または「chalkboard（チョークボード）」と言います！',['classroom']),
mkQ('en1_cl08',1,'「いす」を英語でいうと？','chair',['chare','chiar','cher'],'いすは「chair（チェア）」です！',['classroom']),
mkQ('en1_cl09',1,'「つくえ」を英語でいうと？','desk',['dask','disc','desk'],'つくえは「desk（デスク）」です！',['classroom']),
mkQ('en1_cl10',1,'「ノート」を英語でいうと？','notebook',['note','copybook','workbook'],'ノートは「notebook（ノートブック）」です！日本語の「ノート」のままでは通じないこともあります。',['classroom']),

// ==================== TERM 2 ====================
// 学校の教科
mkQ('en2_sub01',2,'「国語（日本語）」を英語でいうと？','Japanese',['Language','Japanese language','Japanish'],'日本語・国語は「Japanese（ジャパニーズ）」です！',['subjects']),
mkQ('en2_sub02',2,'「算数・数学」を英語でいうと？','math / mathematics',['maths','calculus','numbering'],'算数は「math（マス）」または「mathematics（マセマティクス）」です！',['subjects']),
mkQ('en2_sub03',2,'「理科」を英語でいうと？','science',['sience','scince','siense'],'理科は「science（サイエンス）」です！',['subjects']),
mkQ('en2_sub04',2,'「社会」を英語でいうと？','social studies',['society study','social study','society class'],'社会科は「social studies（ソーシャル スタディーズ）」です！',['subjects']),
mkQ('en2_sub05',2,'「音楽」を英語でいうと？','music',['musical','musick','mussic'],'音楽は「music（ミュージック）」です！',['subjects']),
mkQ('en2_sub06',2,'「体育」を英語でいうと？','P.E. (physical education)',['gym class','sport class','body class'],'体育は「P.E.（ピーイー）」または「physical education（フィジカル エデュケーション）」です！',['subjects']),
mkQ('en2_sub07',2,'「図工・美術」を英語でいうと？','art',['craft','design','drawing'],'図工や美術は「art（アート）」です！',['subjects']),
mkQ('en2_sub08',2,'「外国語（英語）」を英語でいうと？','English',['Foreign language','Englash','Inglish'],'英語の授業は「English（イングリッシュ）」です！',['subjects']),
mkQ('en2_sub09',2,'「道徳」を英語でいうと？','moral education',['ethics class','good class','character study'],'道徳は「moral education（モラル エデュケーション）」です！',['subjects']),
mkQ('en2_sub10',2,'「家庭科」を英語でいうと？','home economics',['home science','house class','family class'],'家庭科は「home economics（ホーム エコノミクス）」です！',['subjects']),
mkQ('en2_sub11',2,'「好きな教科は何ですか？」を英語でいうと？','What subject do you like?',['What class you like?','Which your subject?','What subject are you?'],'「What subject do you like?（何の教科が好きですか）」が正しいです！',['subjects']),
mkQ('en2_sub12',2,'「私は理科が好きです」を英語でいうと？','I like science.',['I like a science.','I enjoy science class.','Science is my like.'],'「I like science.」が正しいです！',['subjects']),
mkQ('en2_sub13',2,'「月曜日に算数の授業があります」を英語でいうと？','I have math on Monday.',['I have math in Monday.','Math is Monday.','I get math on Monday.'],'「have（持っている）」を使って「I have ～ on（曜日）」と言います！',['subjects']),
mkQ('en2_sub14',2,'「あなたは月曜日に何の授業がありますか？」を英語でいうと？','What do you have on Monday?',['What you have Monday?','What class Monday?','What is Monday class?'],'「What do you have on Monday?（月曜日に何がありますか？）」が正しいです！',['subjects']),
mkQ('en2_sub15',2,'「私は体育が得意です」を英語でいうと？','I\'m good at P.E.',['I can P.E. well.','I like P.E. much.','P.E. is my good.'],'得意なものを伝えるには「I\'m good at ～.（アイム グッド アット）」を使います！',['subjects']),

// 時刻・日課
mkQ('en2_t01',2,'「今何時ですか？」を英語でいうと？','What time is it?',['What is the time now?','How time is it?','What clock is it?'],'「What time is it?（ワット タイム イズ イット）」が「今何時ですか？」です！',['time']),
mkQ('en2_t02',2,'「3時です」と英語で答えるには？','It\'s three o\'clock.',['It is three a clock.','The time is three.','Three o\'clock now.'],'「It\'s ～ o\'clock.（イッツ ～ オクロック）」で時刻を言います！',['time']),
mkQ('en2_t03',2,'「何時に起きますか？」を英語でいうと？','What time do you get up?',['What time you wake?','When you get up?','What time are you up?'],'「What time do you get up?（何時に起きますか？）」が正しいです！',['time']),
mkQ('en2_t04',2,'「朝6時に起きます」を英語でいうと？','I get up at six.',['I get up in six.','I up at six.','At six I getting up.'],'時刻を言うときは「at（〜に）」を使います。「I get up at ～.」が正しい形です！',['time']),
mkQ('en2_t05',2,'「何時に寝ますか？」を英語でいうと？','What time do you go to bed?',['What time do you sleep?','When you going bed?','What time you sleep?'],'「go to bed（ベッドに行く＝寝る）」を使います！',['time']),
mkQ('en2_t06',2,'「夜9時に寝ます」を英語でいうと？','I go to bed at nine.',['I sleep at nine p.m.','I bed at nine.','At nine I go bed.'],'「I go to bed at ～.（〜時に寝ます）」が正しい形です！',['time']),
mkQ('en2_t07',2,'「朝ごはんを食べる」を英語でいうと？','eat breakfast',['have breakfast','eat morning','morning eat'],'朝食を食べるは「eat breakfast（イート ブレックファスト）」または「have breakfast」と言います！',['time']),
mkQ('en2_t08',2,'「学校に行く」を英語でいうと？','go to school',['go school','go to the school','go at school'],'「go to school（スクールに行く）」が正しいです。「the」はつけません！',['time']),
mkQ('en2_t09',2,'「午前7時30分」を英語でいうと？','seven thirty a.m.',['seven and thirty a.m.','seven thirty p.m.','a.m. seven thirty'],'「7時30分」は「seven thirty（セブン サーティ）」です。午前は「a.m.（エーエム）」です！',['time']),
mkQ('en2_t10',2,'「a.m.（エーエム）」と「p.m.（ピーエム）」の違いは？','a.m.は午前、p.m.は午後',['a.m.は午後、p.m.は午前','a.m.は朝だけ、p.m.は夜だけ','どちらも同じ意味'],'「a.m.」は「ante meridiem（ラテン語で正午前）」、「p.m.」は「post meridiem（正午後）」の略です！',['time']),
mkQ('en2_t11',2,'「昼食を食べる」を英語でいうと？','eat lunch',['eat noon','have noontime','eat midday'],'昼食は「lunch（ランチ）」、夕食は「dinner（ディナー）」または「supper（サパー）」です！',['time']),
mkQ('en2_t12',2,'「宿題をする」を英語でいうと？','do homework',['make homework','do housework','study homework'],'宿題は「homework（ホームワーク）」、「宿題をする」は「do homework」です！',['time']),
mkQ('en2_t13',2,'「歯を磨く」を英語でいうと？','brush my teeth',['clean my teeth','wash my teeth','brush my tooth'],'「歯磨きする」は「brush my teeth（ブラッシュ マイ ティース）」です。歯は複数なので「teeth」です！',['time']),
mkQ('en2_t14',2,'「お風呂に入る」を英語でいうと？','take a bath',['do a bath','have shower','get bath'],'「お風呂に入る」は「take a bath（テイク ア バス）」、「シャワーを浴びる」は「take a shower」です！',['time']),
mkQ('en2_t15',2,'「テレビを見る」を英語でいうと？','watch TV',['see TV','look TV','watch television'],'「テレビを見る」は「watch TV（ウォッチ ティービー）」です！「see」より「watch」が適切です。',['time']),

// can / can't
mkQ('en2_can01',2,'「私は泳ぐことができます」を英語でいうと？','I can swim.',['I can swimming.','I am able swim.','I can to swim.'],'「〜できる」は「can（キャン）」を使います！「can」の後は動詞の原形（swim）を使います。',['can']),
mkQ('en2_can02',2,'「私は空を飛べません」を英語でいうと？','I can\'t fly.',['I can not to fly.','I cannot flying.','I am not fly.'],'「できない」は「can\'t（キャント）」または「cannot（キャノット）」を使います！',['can']),
mkQ('en2_can03',2,'「あなたは料理ができますか？」を英語でいうと？','Can you cook?',['Do you can cook?','Are you cook?','You can cook?'],'「〜できますか？」と聞くときは「Can you ～?（キャン ユー）」の形にします！',['can']),
mkQ('en2_can04',2,'「はい、できます」を英語でいうと？','Yes, I can.',['Yes, I am.','Yes, I do.','Yes, I will.'],'「Can you ～?」への答えは「Yes, I can.（はい、できます）」です！',['can']),
mkQ('en2_can05',2,'「いいえ、できません」を英語でいうと？','No, I can\'t.',['No, I am not.','No, I don\'t.','No, I won\'t.'],'「Can you ～?」への否定の答えは「No, I can\'t.（いいえ、できません）」です！',['can']),
mkQ('en2_can06',2,'「彼は速く走ることができます」を英語でいうと？','He can run fast.',['He cans run fast.','He can runs fast.','He is can run fast.'],'「He（彼は）」でも「can」はそのままです。「cans」にしてはいけません！',['can']),
mkQ('en2_can07',2,'「私はピアノを弾くことができます」を英語でいうと？','I can play the piano.',['I can play piano.','I can playing piano.','I know play the piano.'],'楽器には「the」をつけます！「play the piano（ザ ピアノ）」が正しいです。',['can']),
mkQ('en2_can08',2,'「私は自転車に乗れます」を英語でいうと？','I can ride a bike.',['I can ride bike.','I can cycling.','I able ride bike.'],'「乗る」は「ride（ライド）」です！「a bike（自転車1台）」と「a」を忘れずに。',['can']),
mkQ('en2_can09',2,'「彼女は上手に絵を描けます」を英語でいうと？','She can draw well.',['She can draws well.','She is able draw.','She cans draw well.'],'「She（彼女）」でも「can」の後は「draw」のまま（原形）です！',['can']),
mkQ('en2_can10',2,'「カメはとても速く走れません」を英語でいうと？','Turtles can\'t run very fast.',['Turtles cannot to run.','Turtles don\'t can run fast.','Turtles are not run fast.'],'「can\'t（できない）」を使います！「don\'t can」のように2つ否定語を重ねてはいけません。',['can']),
mkQ('en2_can11',2,'「あなたは何ができますか？」を英語でいうと？','What can you do?',['What do you can?','What you can do?','Can you what do?'],'「What can you do?（ワット キャン ユー ドゥ）」が正しいです！',['can']),
mkQ('en2_can12',2,'「私は歌を歌うことができます」を英語でいうと？','I can sing.',['I can sing a song.（も正解）','I can to sing.','I can singing.'],'「I can sing.」が基本形です。「I can sing a song.（歌を1曲歌えます）」も正しいです！',['can']),
mkQ('en2_can13',2,'「ピカチュウは電気を使うことができます」を英語でいうと？','Pikachu can use electricity.',['Pikachu is can use.','Pikachu can using.','Pikachu can to use.'],'「can use（使える）」の形です。「can」の後は動詞の原形を忘れずに！',['can']),
mkQ('en2_can14',2,'「私は英語を少し話せます」を英語でいうと？','I can speak a little English.',['I can speak English little.','I can speaking English.','I can little English.'],'「a little（少し）」の位置に注意！「speak（話す）」＋「a little English」が正しい語順です。',['can'],true),
mkQ('en2_can15',2,'「料理ができる人」を英語でいうと？','someone who can cook',['a cooker','a cooking person','cook person'],'「can cook（料理できる）」が使われます。「cooker」はコンロなどの調理器具のことです！',['can'],true),

// 場所・道案内
mkQ('en2_pl01',2,'「学校」を英語でいうと？','school',['sckool','schol','scool'],'学校は「school（スクール）」です！',['places']),
mkQ('en2_pl02',2,'「病院」を英語でいうと？','hospital',['hospitall','hospitale','hopital'],'病院は「hospital（ホスピタル）」です！',['places']),
mkQ('en2_pl03',2,'「駅」を英語でいうと？','station',['stashion','stavion','staton'],'駅は「station（ステーション）」です！',['places']),
mkQ('en2_pl04',2,'「図書館」を英語でいうと？','library',['librery','libaray','libary'],'図書館は「library（ライブラリー）」です！',['places']),
mkQ('en2_pl05',2,'「公園」を英語でいうと？','park',['parc','pack','perk'],'公園は「park（パーク）」です！',['places']),
mkQ('en2_pl06',2,'「お店」を英語でいうと？','shop / store',['mart','market','mall'],'お店は「shop（ショップ）」または「store（ストア）」です！',['places']),
mkQ('en2_pl07',2,'「郵便局」を英語でいうと？','post office',['postoffice','letter office','mail office'],'郵便局は「post office（ポスト オフィス）」です！',['places']),
mkQ('en2_pl08',2,'「銀行」を英語でいうと？','bank',['bonk','banck','benk'],'銀行は「bank（バンク）」です！',['places']),
mkQ('en2_pl09',2,'「右に曲がってください」を英語でいうと？','Turn right.',['Go right.','Turn to right.','Right go.'],'「曲がる」は「turn（ターン）」です！「Turn right.（ターン ライト）」が正しいです。',['places']),
mkQ('en2_pl10',2,'「まっすぐ行ってください」を英語でいうと？','Go straight.',['Go forward.','Go ahead.','Walk straight.'],'「まっすぐ」は「straight（ストレート）」です！「Go straight.」が正しいです。',['places']),
mkQ('en2_pl11',2,'「どこに行きたいですか？」を英語でいうと？','Where do you want to go?',['Where you want go?','Where to go you?','What place do you go?'],'「Where do you want to go?（どこに行きたいですか？）」が正しいです！',['places']),
mkQ('en2_pl12',2,'「左に曲がってください」を英語でいうと？','Turn left.',['Turn right.','Go left.','Left turn on.'],'左は「left（レフト）」です！「Turn left.」が正しいです。',['places']),
mkQ('en2_pl13',2,'「〇〇はどこですか？」と場所を聞くには？','Where is ○○?',['What is ○○?','Where are ○○?','How is ○○?'],'「Where is ～?（ウェア イズ）」で場所を聞けます！',['places']),
mkQ('en2_pl14',2,'「〜の近くに」を英語でいうと？','near ~',['close by ~','next ~','nearby to ~'],'「near（ニア）」で「〜の近くに」を表します！「near the park（公園の近くに）」のように使います。',['places']),
mkQ('en2_pl15',2,'「〜の前に」を英語でいうと？','in front of ~',['before ~','ahead of ~','in the front ~'],'「in front of ～（イン フロント オブ）」で「〜の前に」を表します！',['places']),

// スポーツ
mkQ('en2_sp01',2,'「サッカー」を英語でいうと？','soccer / football',['soccar','socker','footbal'],'サッカーは「soccer（ソッカー）」（アメリカ）または「football（フットボール）」（イギリスなど）と言います！',['sports']),
mkQ('en2_sp02',2,'「野球」を英語でいうと？','baseball',['base ball','basball','baseball'],'野球は「baseball（ベースボール）」です！「base（塁）」＋「ball」ですね。',['sports']),
mkQ('en2_sp03',2,'「バスケットボール」を英語でいうと？','basketball',['basket ball','basquetball','basketbol'],'バスケットボールは「basketball（バスケットボール）」です！',['sports']),
mkQ('en2_sp04',2,'「水泳」を英語でいうと？','swimming',['swiming','swimmng','swimm'],'水泳は「swimming（スウィミング）」です！「m」が2つ続きます。',['sports']),
mkQ('en2_sp05',2,'「テニス」を英語でいうと？','tennis',['tenis','teniss','tennes'],'テニスは「tennis（テニス）」です！「n」が2つ続きます。',['sports']),
mkQ('en2_sp06',2,'「バレーボール」を英語でいうと？','volleyball',['vollyball','voleayball','voleyball'],'バレーボールは「volleyball（バリーボール）」です！',['sports']),
mkQ('en2_sp07',2,'「柔道」を英語でいうと？','judo',['judou','jiudo','jyudo'],'柔道は「judo（ジュードー）」です！世界共通の日本語です。',['sports']),
mkQ('en2_sp08',2,'「スキー」を英語でいうと？','skiing',['ski','skiying','skieing'],'スキーは「skiing（スキーイング）」です！',['sports']),
mkQ('en2_sp09',2,'「陸上競技（走ること）」を英語でいうと？','running / track and field',['athletics','racing','running sports'],'走ることは「running（ランニング）」、陸上競技は「track and field（トラック アンド フィールド）」です！',['sports']),
mkQ('en2_sp10',2,'「サッカーをする」を英語でいうと？','play soccer',['do soccer','practice soccer','make soccer'],'スポーツ（ボール系）は「play（プレイ）」を使います！「play soccer/baseball/basketball」などです。',['sports']),
mkQ('en2_sp11',2,'「水泳をする」を英語でいうと？','swim',['play swim','do swimming','make swimming'],'水泳・陸上などは「swim（スウィム）」「run（ラン）」のように動詞1語で言います！「play」ではありません。',['sports'],true),
mkQ('en2_sp12',2,'「好きなスポーツは何ですか？」を英語でいうと？','What sport do you like?',['Which sport you play?','What sport are you?','Do you sport?'],'「What sport do you like?（何のスポーツが好きですか？）」が正しいです！',['sports']),

// 職業・will/want to be
mkQ('en2_job01',2,'「医者」を英語でいうと？','doctor',['docter','dactor','doktor'],'医者は「doctor（ドクター）」です！',['jobs']),
mkQ('en2_job02',2,'「先生」を英語でいうと？','teacher',['teatcher','teecher','techer'],'先生は「teacher（ティーチャー）」です！',['jobs']),
mkQ('en2_job03',2,'「消防士」を英語でいうと？','firefighter',['fireman','fireworker','firefiter'],'消防士は「firefighter（ファイアーファイター）」です！「fire（火）」＋「fighter（戦う人）」ですね。',['jobs']),
mkQ('en2_job04',2,'「警察官」を英語でいうと？','police officer',['policeman','cop officer','guard officer'],'警察官は「police officer（ポリス オフィサー）」または「police officer」です！',['jobs']),
mkQ('en2_job05',2,'「料理人・シェフ」を英語でいうと？','cook / chef',['cooker','cookman','cheff'],'料理人は「cook（クック）」、プロの料理長は「chef（シェフ）」です！「cooker」は料理道具のことです。',['jobs']),
mkQ('en2_job06',2,'「歌手」を英語でいうと？','singer',['songman','sanger','singing'],'歌手は「singer（シンガー）」です！「sing（歌う）」＋「er（人）」ですね。',['jobs']),
mkQ('en2_job07',2,'「宇宙飛行士」を英語でいうと？','astronaut',['spaceman','astrounaut','astronot'],'宇宙飛行士は「astronaut（アストロノート）」です！かっこいい単語ですね。',['jobs']),
mkQ('en2_job08',2,'「将来の夢は何ですか？」を英語でいうと？','What do you want to be?',['What will you be?','What is your dream?','What you want be?'],'「What do you want to be?（将来何になりたいですか？）」が正しい表現です！',['jobs']),
mkQ('en2_job09',2,'「私は医者になりたいです」を英語でいうと？','I want to be a doctor.',['I want be doctor.','I will be a doctor.','I want to a doctor.'],'「want to be（〜になりたい）」を使います！「a」を忘れずに。',['jobs']),
mkQ('en2_job10',2,'「パイロット」を英語でいうと？','pilot',['pilote','pilott','pailot'],'パイロットは「pilot（パイロット）」です！',['jobs']),
mkQ('en2_job11',2,'「ミュージシャン（音楽家）」を英語でいうと？','musician',['musicman','musisian','musision'],'音楽家は「musician（ミュージシャン）」です！',['jobs']),
mkQ('en2_job12',2,'「科学者」を英語でいうと？','scientist',['scienceman','sientist','scientest'],'科学者は「scientist（サイエンティスト）」です！「science（理科）」から来ていますね。',['jobs']),

// 天気・季節
mkQ('en2_w01',2,'「晴れ」を英語でいうと？','sunny',['sunny and clear','sunnny','sunney'],'晴れは「sunny（サニー）」です！「sun（太陽）」から来ています。',['weather']),
mkQ('en2_w02',2,'「くもり」を英語でいうと？','cloudy',['cloddy','cloudly','cloude'],'くもりは「cloudy（クラウディ）」です！「cloud（雲）」＋「y」ですね。',['weather']),
mkQ('en2_w03',2,'「雨」を英語でいうと？','rainy',['rain','rainly','rany'],'雨の日は「rainy（レイニー）」です！「rain（雨）」から来ています。',['weather']),
mkQ('en2_w04',2,'「雪が降っている」を英語でいうと？','It\'s snowy.',['It snow.','It is snowing.（も正解）','The snow falls.'],'「It\'s snowy.（ユキが降っている）」または「It\'s snowing.」が正しいです！',['weather']),
mkQ('en2_w05',2,'「今日の天気はどうですか？」を英語でいうと？','How\'s the weather today?',['What is the weather?','How weather today?','How is today?'],'「How\'s the weather today?（ハウズ ザ ウェザー トゥデイ）」が正しいです！',['weather']),
mkQ('en2_w06',2,'「春」を英語でいうと？','spring',['sprng','spiring','spling'],'春は「spring（スプリング）」です！',['weather']),
mkQ('en2_w07',2,'「夏」を英語でいうと？','summer',['sumer','sommar','summmer'],'夏は「summer（サマー）」です！',['weather']),
mkQ('en2_w08',2,'「秋」を英語でいうと？','fall / autumn',['autumn fall','falm','autam'],'秋は「fall（フォール）」（アメリカ）または「autumn（オータム）」（イギリス）です！',['weather']),
mkQ('en2_w09',2,'「冬」を英語でいうと？','winter',['wintter','wintre','vinter'],'冬は「winter（ウィンター）」です！',['weather']),
mkQ('en2_w10',2,'「好きな季節はなんですか？」を英語でいうと？','What season do you like?',['Which season you like?','What is your season?','What season are you?'],'「What season do you like?（何の季節が好きですか？）」が正しいです！',['weather']),

// shopping / would like
mkQ('en2_shop01',2,'「〜をください」とお店で頼む言い方は？','I\'d like ~, please.',['I want ~ please.','Give me ~.','I need ~.'],'「I\'d like ～（アイド ライク）」は「〜をいただきたいのですが」という丁寧な言い方です！',['shopping']),
mkQ('en2_shop02',2,'「これはいくらですか？」を英語でいうと？','How much is this?',['How many is this?','What price is this?','How cost is this?'],'値段を聞くときは「How much（ハウ マッチ）」を使います！',['shopping']),
mkQ('en2_shop03',2,'「〜はありますか？」とお店で聞くには？','Do you have ~?',['Have you ~?','Is there ~?','Can you have ~?'],'「Do you have ～?（〜はありますか？）」が正しいです！',['shopping']),
mkQ('en2_shop04',2,'「500円です」と英語でいうと？','It\'s five hundred yen.',['It five hundred yen.','The price is 500.','Five hundred yen it is.'],'「It\'s ～ yen.（イッツ ～ エン）」で値段を伝えます！',['shopping']),
mkQ('en2_shop05',2,'「ラーメンを1つください」をていねいに英語でいうと？','I\'d like one ramen, please.',['I want one ramen please.','Give me ramen one.','One ramen I need.'],'「I\'d like ～, please.」がとても丁寧な注文の仕方です！',['shopping']),

// 国・言語
mkQ('en2_ctr01',2,'「日本」を英語でいうと？','Japan',['Japon','Japang','Nippon'],'日本は「Japan（ジャパン）」です！',['countries']),
mkQ('en2_ctr02',2,'「アメリカ」を英語でいうと？','America / the United States',['American','USA only','Amerca'],'アメリカは「America」または「the United States（ユナイテッド ステイツ）」です。略して「the U.S.」とも言います！',['countries']),
mkQ('en2_ctr03',2,'「イギリス」を英語でいうと？','the United Kingdom / the UK',['England','Britain only','Eengland'],'イギリスは「the United Kingdom（ユナイテッド キングダム）」、略して「the UK」です。「England」はその一部です！',['countries'],true),
mkQ('en2_ctr04',2,'「フランス」を英語でいうと？','France',['Franse','Frans','Frenz'],'フランスは「France（フランス）」です！',['countries']),
mkQ('en2_ctr05',2,'「オーストラリア」を英語でいうと？','Australia',['Austrailia','Australya','Ustralia'],'オーストラリアは「Australia（オーストレーリア）」です！',['countries']),
mkQ('en2_ctr06',2,'「中国」を英語でいうと？','China',['Chine','Cina','Chaina'],'中国は「China（チャイナ）」です！',['countries']),
mkQ('en2_ctr07',2,'「韓国」を英語でいうと？','Korea',['Corea','Koree','Koria'],'韓国は「Korea（コリア）」です！',['countries']),
mkQ('en2_ctr08',2,'「ブラジル」を英語でいうと？','Brazil',['Brasil','Brazill','Brazile'],'ブラジルは「Brazil（ブラジル）」です！',['countries']),
mkQ('en2_ctr09',2,'「〜に行きたいです」を英語でいうと？','I want to go to ~.',['I want go ~.','I\'d like go to ~.','I want to ~.'],'「I want to go to ～.（〜に行きたいです）」が正しいです！',['countries']),
mkQ('en2_ctr10',2,'「どこに行きたいですか？」を英語でいうと？','Where do you want to go?',['Where you want go?','What country you go?','Where to you go?'],'「Where do you want to go?（どこに行きたいですか？）」が正しいです！',['countries']),

// ==================== TERM 3 ====================
// 3人称単数・he/she
mkQ('en3_he01',3,'「彼は〜が好きです」を英語でいうと？','He likes ~.',['He like ~.','Him likes ~.','He is like ~.'],'「He（彼は）」が主語のとき、「like」に「s」がついて「likes」になります！これを「3単現のs」といいます。',['he_she']),
mkQ('en3_he02',3,'「彼女は〜が好きです」を英語でいうと？','She likes ~.',['She like ~.','Her likes ~.','She is likes ~.'],'「She（彼女は）」が主語のとき、「like」→「likes」と「s」がつきます！',['he_she']),
mkQ('en3_he03',3,'「彼は毎日学校に行きます」を英語でいうと？','He goes to school every day.',['He go to school every day.','He gos to school every day.','He is go to school.'],'「go」は3単現で「goes（ゴーズ）」に変わります！「s」だけでなく「es」がつく動詞もあります。',['he_she']),
mkQ('en3_he04',3,'「彼女はピアノを弾くことができます」を英語でいうと？','She can play the piano.',['She cans play the piano.','She can plays the piano.','Her can play the piano.'],'「can」の後の「can」は変化しません！「cans」や「can plays」はNGです。',['he_she']),
mkQ('en3_he05',3,'「あの人（男性）は誰ですか？」を英語でいうと？','Who is he?',['Who is him?','Who is that?','Who he is?'],'「Who is he?（フー イズ ヒー）」が正しいです！',['he_she']),
mkQ('en3_he06',3,'「彼のお父さんはシェフです」を英語でいうと？','His father is a chef.',['He\'s father is a chef.','Him father is a chef.','He father is chef.'],'「彼の〜」は「His（ヒズ）」を使います！「He\'s」は「He is」の短縮形なので違います。',['he_she']),
mkQ('en3_he07',3,'「彼女の趣味は読書です」を英語でいうと？','Her hobby is reading.',['She\'s hobby is reading.','Hers hobby is reading.','She hobby reading.'],'「彼女の〜」は「Her（ハー）」を使います！',['he_she']),
mkQ('en3_he08',3,'「彼は英語が話せます」を英語でいうと？','He can speak English.',['He can speaks English.','He cans speak English.','Him can speak English.'],'「can」の後は動詞の原形！「speaks」ではなく「speak」です。',['he_she']),
mkQ('en3_he09',3,'「彼女は上手に歌を歌います」を英語でいうと？','She sings well.',['She sing well.','She is singing well.','She sings good.'],'「sing→sings（シングズ）」と3単現の「s」がつきます！「good」ではなく「well（副詞）」を使います。',['he_she'],true),
mkQ('en3_he10',3,'「ザシアンはとても強い」を英語でいうと？','Zacian is very strong.',['Zacian are very strong.','Zacian be very strong.','Zacian is very stronger.'],'「is（イズ）」を使います。比べていないのに「stronger（より強い）」にしてはいけません！',['he_she']),

// 形容詞・比較
mkQ('en3_adj01',3,'「大きい」を英語でいうと？','big / large',['small','tall','wide'],'大きいは「big（ビッグ）」または「large（ラージ）」です！',['adjectives']),
mkQ('en3_adj02',3,'「小さい」を英語でいうと？','small / little',['tiny only','smale','samll'],'小さいは「small（スモール）」または「little（リトル）」です！',['adjectives']),
mkQ('en3_adj03',3,'「速い」を英語でいうと？','fast / quick',['speed','speedy','rushing'],'速いは「fast（ファスト）」または「quick（クイック）」です！',['adjectives']),
mkQ('en3_adj04',3,'「遅い（おそい）」を英語でいうと？','slow',['slowly','sloe','sloow'],'遅いは「slow（スロー）」です！「slowly」は副詞（ゆっくり）です。',['adjectives']),
mkQ('en3_adj05',3,'「強い」を英語でいうと？','strong',['strenght','stong','srong'],'強いは「strong（ストロング）」です！',['adjectives']),
mkQ('en3_adj06',3,'「かわいい」を英語でいうと？','cute',['cutie','cuute','kyute'],'かわいいは「cute（キュート）」です！',['adjectives']),
mkQ('en3_adj07',3,'「美しい・きれい」を英語でいうと？','beautiful',['butiful','beautifull','beutiful'],'美しいは「beautiful（ビューティフル）」です！「beauty（美）」から来ています。',['adjectives']),
mkQ('en3_adj08',3,'「おもしろい・楽しい」を英語でいうと？','fun / interesting',['funny only','enjoy','entertain'],'楽しいは「fun（ファン）」、興味深いは「interesting（インタレスティング）」です！',['adjectives']),
mkQ('en3_adj09',3,'「難しい」を英語でいうと？','difficult / hard',['hardly','diffcult','hardest'],'難しいは「difficult（ディフィカルト）」または「hard（ハード）」です！',['adjectives']),
mkQ('en3_adj10',3,'「簡単な・やさしい」を英語でいうと？','easy',['easey','eazy','easily'],'簡単なは「easy（イージー）」です！「easily」は副詞（簡単に）です。',['adjectives']),
mkQ('en3_adj11',3,'「高い（値段・背が高い）」を英語でいうと？','high / tall',['height','expensive only','up'],'背が高いは「tall（トール）」、値段が高いは「expensive（エクスペンシブ）」または「high」です！',['adjectives']),
mkQ('en3_adj12',3,'「新しい」を英語でいうと？','new',['newer','nue','gnu'],'新しいは「new（ニュー）」です！',['adjectives']),
mkQ('en3_adj13',3,'「古い」を英語でいうと？','old',['aged','ould','ohld'],'古いは「old（オールド）」です！年取っている意味もあります。',['adjectives']),
mkQ('en3_adj14',3,'「Aはbより〜です」の比較の言い方は？','A is ～er than B.',['A is more ～ than B.（一部）','A is ～ more B.','A ～er B.'],'短い形容詞は「〜er than」を使います！例：「Pikachu is faster than Snorlax.（ピカチュウはカビゴンより速い）」',['adjectives'],true),
mkQ('en3_adj15',3,'「pikachu is faster than snorlax」の意味は？','ピカチュウはカビゴンより速い',['カビゴンはピカチュウより速い','ピカチュウとカビゴンは同じ速さ','ピカチュウはカビゴンほど速くない'],'「faster than（ファスター ザン）」は「〜より速い」という比較の表現です！',['adjectives']),
mkQ('en3_adj16',3,'「hot（暑い）」の反対語は？','cold',['cool','frozen','warm'],'「hot（暑い）」の反対は「cold（コールド：寒い）」です。「cool」は「涼しい」です！',['adjectives']),
mkQ('en3_adj17',3,'「happy（幸せ）」の反対語は？','sad',['unhappy（も正解）','mad','bad'],'「happy（幸せ）」の反対は「sad（サッド：悲しい）」です！',['adjectives']),
mkQ('en3_adj18',3,'「long（長い）」の反対語は？','short',['small','brief','low'],'「long（長い）」の反対は「short（ショート：短い）」です！',['adjectives']),
mkQ('en3_adj19',3,'「hungry（お腹がすいた）」の反対語は？','full',['satisfied','not hungry','fed'],'「hungry（お腹すいた）」の反対は「full（フル：お腹いっぱい）」です！',['adjectives']),
mkQ('en3_adj20',3,'「light（軽い・明るい）」の反対語は？','heavy / dark',['hard','cold','strong'],'「軽い」の反対は「heavy（ヘビー：重い）」、「明るい」の反対は「dark（ダーク：暗い）」です！',['adjectives']),

// 世界の文化・国
mkQ('en3_cul01',3,'「イタリア料理」で有名な食べ物は英語で？','pizza and pasta',['pizza and sushi','pasta and baguette','spaghetti and sushi'],'イタリアは「pizza（ピザ）」と「pasta（パスタ）」で有名です！',['world_culture']),
mkQ('en3_cul02',3,'「フランスのパン」を英語でいうと？','baguette',['French bread','crusty bread','long bread'],'フランスの細長いパンは「baguette（バゲット）」といいます！',['world_culture']),
mkQ('en3_cul03',3,'インドカレーは英語で？','curry',['Indian sauce','spicy soup','currye'],'カレーは「curry（カリー）」です！インドが発祥の料理です。',['world_culture']),
mkQ('en3_cul04',3,'「アメリカの有名な食べ物」といえば？','hamburger',['hot dog only','sandwich','steak'],'アメリカといえば「hamburger（ハンバーガー）」が有名です！',['world_culture']),
mkQ('en3_cul05',3,'「世界で最も話されている英語の国」はどこ？','the United States',['the United Kingdom','Australia','Canada'],'話者数ではアメリカ（the United States）が最も多い英語話者を持ちます！',['world_culture']),
mkQ('en3_cul06',3,'「日本文化として世界に広まっているもの」として正しいのは？','sushi and anime',['hamburger and pizza','curry and baguette','tacos and samba'],'「sushi（寿司）」と「anime（アニメ）」は世界中で人気の日本文化です！',['world_culture']),
mkQ('en3_cul07',3,'「世界遺産」を英語でいうと？','World Heritage Site',['World History Place','World Famous Site','World Legacy Site'],'世界遺産は「World Heritage Site（ワールド ヘリテージ サイト）」です！',['world_culture']),
mkQ('en3_cul08',3,'「サンバ」で有名な国はどこ？','Brazil',['Argentina','Mexico','Colombia'],'サンバは「Brazil（ブラジル）」が発祥の音楽・ダンスです！',['world_culture']),
mkQ('en3_cul09',3,'「タコス」で有名な国はどこ？','Mexico',['Spain','Colombia','Peru'],'タコスは「Mexico（メキシコ）」の有名な料理です！',['world_culture']),
mkQ('en3_cul10',3,'「キムチ」で有名な国はどこ？','Korea',['China','Japan','Vietnam'],'キムチは「Korea（韓国）」の有名な発酵食品です！',['world_culture']),

// 将来の夢
mkQ('en3_dream01',3,'「私はサッカー選手になりたいです」を英語でいうと？','I want to be a soccer player.',['I want be soccer player.','I will soccer player.','I want to soccer player.'],'「I want to be a ～.（〜になりたい）」が正しいです！「to be」を忘れずに。',['dreams']),
mkQ('en3_dream02',3,'「彼は宇宙飛行士になりたいです」を英語でいうと？','He wants to be an astronaut.',['He want to be an astronaut.','He wants be astronaut.','He is wanting astronaut.'],'3単現なので「wants（ウォンツ）」になります！',['dreams']),
mkQ('en3_dream03',3,'「あなたは将来何になりたいですか？」を英語でいうと？','What do you want to be in the future?',['What will you be?','What do you want be?','What do you to be?'],'「What do you want to be in the future?（将来何になりたいですか？）」が正しいです！',['dreams']),
mkQ('en3_dream04',3,'「医者」を英語でいうと？','doctor',['healer','medical','nurseman'],'医者は「doctor（ドクター）」です！',['dreams']),
mkQ('en3_dream05',3,'「保育士・子供の面倒をみる人」を英語でいうと？','childcare worker / nursery teacher',['child teacher','baby keeper','kinder teacher'],'保育士は「childcare worker（チャイルドケア ワーカー）」です！',['dreams']),
mkQ('en3_dream06',3,'「農家の人・農業をする人」を英語でいうと？','farmer',['agriculture','fielder','agri-worker'],'農家の人は「farmer（ファーマー）」です！',['dreams']),
mkQ('en3_dream07',3,'「作家・文章を書く人」を英語でいうと？','writer',['author（も正解）','writter','writeman'],'作家は「writer（ライター）」または「author（オーサー）」です！',['dreams']),
mkQ('en3_dream08',3,'「デザイナー」を英語でいうと？','designer',['design person','desiner','designner'],'デザイナーは「designer（デザイナー）」です！',['dreams']),
mkQ('en3_dream09',3,'「プログラマー」を英語でいうと？','programmer',['programer','computer maker','coder（も使われる）'],'プログラマーは「programmer（プログラマー）」です！',['dreams']),
mkQ('en3_dream10',3,'「私の夢はポケモントレーナーになることです」を英語でいうと？','My dream is to be a Pokémon trainer.',['My dream is Pokémon trainer.','I dream Pokémon trainer.','My dream is be trainer.'],'「My dream is to be ～.（私の夢は〜になることです）」が正しいです！',['dreams']),

// 総復習・文法
mkQ('en3_rev01',3,'「私は〜があります（持っています）」を英語でいうと？','I have ~.',['I got ~.','I hold ~.','I own ~.'],'「持っている・いる」は「have（ハブ）」を使います！',['review']),
mkQ('en3_rev02',3,'「there is（ゼア イズ）」と「there are（ゼア アー）」の使い分けは？','単数のとき is、複数のとき are',['名詞が長いとき are、短いとき is','どちらでもよい','人のときis、もののときare'],'「There is ～.（〜がひとつあります）」、「There are ～.（〜が複数あります）」です！',['review']),
mkQ('en3_rev03',3,'「これは何ですか？」を英語でいうと？','What is this?',['What this is?','What are this?','This is what?'],'「What is this?（ワット イズ ディス）」が正しいです！',['review']),
mkQ('en3_rev04',3,'「どちらが好きですか？A それとも B？」を英語でいうと？','Which do you like, A or B?',['What do you like, A or B?','Which like you?','Do you like which?'],'選択を聞くとき「Which（ウィッチ：どちら）」を使います！「What（何）」ではありません。',['review']),
mkQ('en3_rev05',3,'「〜の上に」を英語でいうと？','on',['in','above','up'],'「〜の上に（接している）」は「on（オン）」です！「above」は「〜の上の空間」です。',['review']),
mkQ('en3_rev06',3,'「〜の中に」を英語でいうと？','in',['inside only','into','within'],'「〜の中に」は「in（イン）」です！「The cat is in the box.（ネコは箱の中にいます）」のように使います。',['review']),
mkQ('en3_rev07',3,'「〜の隣に」を英語でいうと？','next to ~',['near ~','beside ~（も正解）','by side ~'],'「next to ～（ネクスト トゥ）」で「〜の隣に」を表します！',['review']),
mkQ('en3_rev08',3,'「私たち」を英語でいうと？','we',['us','our','ours'],'「私たち（主語）」は「we（ウィー）」です！「us」は「私たちを・に」という目的語の形です。',['review']),
mkQ('en3_rev09',3,'「〜しましょう！」と提案するときは？','Let\'s ~!',['We do ~!','Shall we ~!（も使える）','Go ~!'],'「Let\'s ～!（レッツ）」で「〜しましょう！」と誘えます！「Let\'s play soccer!（サッカーしよう！）」のように使います。',['review']),
mkQ('en3_rev10',3,'「I（私）」の代わりに使う「私を・私に」の形は？','me',['my','mine','myself'],'「私（目的語）」は「me（ミー）」です！「Tell me.（教えて）」や「Look at me.（私を見て）」のように使います。',['review']),
mkQ('en3_rev11',3,'「〜してもいいですか？（許可を求める）」を英語でいうと？','Can I ~? / May I ~?',['Do I ~?','Shall I ~?','Would I ~?'],'「Can I ～?（キャン アイ）」または「May I ～?（メイ アイ）」で許可を求めます！',['review']),
mkQ('en3_rev12',3,'「一緒に〇〇しませんか？」と誘うときは？','Would you like to ~ with me?',['Do you want with me?','Let\'s ~ together?','Shall you ~ with me?'],'「Would you like to ～?（ウッジュー ライク トゥ）」はとても丁寧な誘い方です！',['review'],true),
mkQ('en3_rev13',3,'「好き（like）」「大好き（love）」「嫌い（hate）」を弱い順に並べると？','like → love → hate',['hate → like → love','love → like → hate','like → hate → love'],'好意の強さは「like（好き）」→「love（大好き）」、その反対が「hate（嫌い）」です！',['review']),
mkQ('en3_rev14',3,'「あなたに英語で手紙を書きます」を英語でいうと？','I\'ll write a letter to you in English.',['I write letter English to you.','I will to write English letter.','English letter I write you.'],'「write ～ to you（あなたに〜を書く）」「in English（英語で）」の語順に注意！',['review'],true),
mkQ('en3_rev15',3,'英語の文の最初は何にする？','大文字（capital letter）',['小文字（lowercase）','どちらでもよい','記号（punctuation）'],'英語の文は必ず「大文字」で始めます！また文の最後は「.（ピリオド）」「?（クエスチョンマーク）」「!（エクスクラメーション）」をつけます。',['review']),

// 追加語彙・フレーズ
mkQ('en3_voc01',3,'「好きな教科は何ですか？私は算数が好きです」の英語の会話で正しいのは？','What subject do you like? — I like math.',['Which class you like? — Math I like.','What do you like subject? — Like math I.','Do you like subject? — I math like.'],'「What subject do you like?」「I like ～.」の形が正しいです！',['vocabulary']),
mkQ('en3_voc02',3,'「教えてください」を英語でいうと？','Please tell me.',['Please teach me.（教育の意味）','Say me please.','Tell please me.'],'「tell me（教えてください・言ってください）」と「teach me（教えてください・指導してください）」は少し意味が違います！',['vocabulary']),
mkQ('en3_voc03',3,'「もう一度言ってください」を英語でいうと？','Please say that again.',['One more please.','Repeat please.','Say again please.（も通じる）'],'「Please say that again.（もう一度言ってください）」が丁寧な言い方です！',['vocabulary']),
mkQ('en3_voc04',3,'「私には兄が1人います」を英語でいうと？','I have one older brother.',['I got one older brother.','I am one older brother.','There is one older brother.'],'「I have ～.（〜がいます・あります）」を使います！',['vocabulary']),
mkQ('en3_voc05',3,'「私には兄弟がいません」を英語でいうと？','I don\'t have any brothers or sisters.',['I have no brothers or sisters.（も正解）','I am not have brothers.','I no have siblings.'],'「don\'t have（持っていない）」を使います！「I have no ～.」も正しいです。',['vocabulary']),
mkQ('en3_voc06',3,'「英語が好きですか？」と聞かれて「はい、でも難しいです」と答えるには？','Yes, I do. But it\'s difficult.',['Yes I like. But hard.','Yes, it\'s. But difficult.','I like yes but hard.'],'「Yes, I do.」で肯定し、「But it\'s ～（でも〜です）」でつなぎます！',['vocabulary']),
mkQ('en3_voc07',3,'「もっとゆっくり話してください」を英語でいうと？','Please speak more slowly.',['Please speak slower.','Speak slow please more.','More slowly speaking please.'],'「speak more slowly（もっとゆっくり話す）」が正しいです！',['vocabulary']),
mkQ('en3_voc08',3,'「〜について話す」を英語でいうと？','talk about ~',['talk of ~','speak about ~（も可）','talk in ~'],'「talk about ～（〜について話す）」が正しいです！',['vocabulary']),
mkQ('en3_voc09',3,'「日本の食べ物はどう思いますか？」と聞くには？','What do you think of Japanese food?',['How do you think Japanese food?','What Japanese food do you like?','What is your think about food?'],'「What do you think of ～?（〜についてどう思いますか？）」が正しいです！',['vocabulary'],true),
mkQ('en3_voc10',3,'「私の好きな季節は夏です」を英語でいうと？','My favorite season is summer.',['I like summer season.','My season best is summer.','My favorit season summer.'],'「My favorite ～ is ～.（私のお気に入りの〜は〜です）」の形を使います！',['vocabulary']),
mkQ('en3_voc11',3,'「私は毎日英語を勉強しています」を英語でいうと？','I study English every day.',['I am studying English every day.（も正解）','I study every day English.','I English study daily.'],'「I study ～ every day.」が基本形です！現在進行形「I am studying」も使えます。',['vocabulary']),
mkQ('en3_voc12',3,'「この夏休みに何をしましたか？」を英語でいうと？','What did you do this summer vacation?',['What you did summer?','What do you do in summer?','What you summer do?'],'過去のことを聞くときは「did（ディド）」を使います！「do」ではありません。',['vocabulary'],true),
mkQ('en3_voc13',3,'「私は昨日図書館に行きました」を英語でいうと？','I went to the library yesterday.',['I go to library yesterday.','I went library yesterday.','I did go to library.'],'過去形：「go→went（ウェント）」になります。「the library（図書館）」に「the」をつけます！',['vocabulary'],true),
mkQ('en3_voc14',3,'「いつか世界中を旅したいです」を英語でいうと？','I want to travel around the world someday.',['I want travel world someday.','I will travel world some day.','I like travel world someday.'],'「want to travel（旅したい）」「around the world（世界中を）」「someday（いつか）」です！',['vocabulary']),
mkQ('en3_voc15',3,'「友達に英語でメッセージを送れますか？」という質問の正しい英語は？','Can you send a message in English to your friend?',['Can you send message English?','You can message friend English?','Can English message your friend?'],'「send a message（メッセージを送る）」「in English（英語で）」「to your friend（友達に）」の語順です！',['vocabulary'],true),

];
